version: '3.8'

services:
  mariadb:
    image: postgres:latest
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local