name: Go CI/CD Pipeline for Release

on:
  workflow_dispatch:
    inputs:
      dbms_cleaner:
        description: 'Version du build'
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      # Installer les dépendances Go
      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build
        run: go build -v .

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: DBMSCleaner
          retention-days: 1
        if: matrix.os != 'windows-latest'

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: DBMSCleaner.exe
          retention-days: 1
        if: matrix.os == 'windows-latest'

  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-ubuntu-latest
          path: ubuntu

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-macos-latest
          path: macos

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-windows-latest
          path: windows

      - name: Renamer
        run: |
          mv ubuntu/DBMSCleaner DBMSCleaner_ubuntu
          mv macos/DBMSCleaner DBMSCleaner_macos
          mv windows/DBMSCleaner.exe DBMSCleaner_windows.exe

      - name: Creating release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.dbms_cleaner }}
          name: ${{ github.event.inputs.dbms_cleaner }}
          draft: false
          prerelease: false
          files: |
            DBMSCleaner_ubuntu
            DBMSCleaner_macos
            DBMSCleaner_windows.exe
          token: ${{ secrets.GITHUB_TOKEN }}


